[package]
name = "tetris"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]

[features]
empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]

[dependencies.amethyst]
version = "0.11.0"
features = ["vulkan"]
